SCC-4019: Account API documentation
NYPL/research-catalog pull request #125
Opened 2024-03-04 20:56 UTC by 7emansell

Resolves [SCC-4019](https://jira.nypl.org/browse/SCC-4019).

Documents Sierra API endpoints for account page.

2024-03-04 20:58 UTC, 7emansell commented
Not sure what else to include for now, since I don't want to just repeat the TAD. But open to adding more sections etc.

2024-03-04 21:36 UTC, EdwinGuzman reviewed
Just a minor update for one request body example.

This might be too much but what do you think about keeping this table as an introduction for this document but remove the "Example request body..." column?

Then you can make each endpoint a section and have it's expected request query and/or body parameters and what the success/error response looks like. Examples of what I'm thinking https://github.com/NYPL/digital-collections?tab=readme-ov-file#individual-lane---get-apilanesslug and https://github.com/NYPL/dgx-patron-creator-service/wiki/API-V0.3

I don't want this to hold up dev work so this could be worked on at the end.

2024-03-06 21:37 UTC, 7emansell commented
> This might be too much but what do you think about keeping this table as an introduction for this document but remove > the "Example request body..." column?

That sounds good to me!

2024-03-28 18:27 UTC, 7emansell commented on accountREADME.md
> +    message: 'Pin updated to 7890'
I anticipate changing this in the update PIN pr since I don't think it's a good idea to return the new pin in the response :)

2024-03-28 21:12 UTC, EdwinGuzman requested changes
403 are usually for forbidden endpoints and the endpoints do return this when the patron is not authenticated.

For other errors, it looks like the error code from Sierra is propagated to the returned response. So there should be more exampleFailureResponse objects with multiple 4XX statuses.

2024-03-28 21:15 UTC, EdwinGuzman commented on accountREADME.md
> +    status: 403,
Regarding the 403 response, there are multiple ones returned for this endpoint (and possibly others):

```
status: 403,
message: "No authenticated patron"
```
and
```
status: 403,
message: "Authenticated patron does not own this checkout"
```

List them all down. Ideally, I think a response status code should only have one error message but that can be discussed later.

2024-03-29 13:52 UTC, 7emansell commented
@EdwinGuzman For every endpoint, getting a 403 for a patron that's not authenticated or doesn't match the item they're updating is possible. Should I collect those example responses in one place or just repeat them for each? Also, a recurring theme with Sierra work is that we can't predict every possible thing that it will return, but we know it will use code 403 for many different errors. Ideally, once logging is implemented, those errors will be recorded on Cloudwatch. What would be the best way to represent this in with the examples in the docs?

2024-03-29 17:45 UTC, EdwinGuzman commented on accountREADME.md
> +If the request fails because it's rejected by Sierra (a common example is a checkout being renewed too many times), it will return a `4XX` status, with a message from Sierra.
You also get the status from the rejected Sierra request? It's mostly likely a 400 bad request or something else? Not for this PR but either return whatever Sierra returns or set a status other than 403 for bad Sierra requests.

2024-03-29 17:46 UTC, EdwinGuzman approved these changes
Looks good. I'm being picky about the 403 for Sierra-related errors but that's a potential code update and not a readme update.

2024-03-29 17:53 UTC, 7emansell commented
@EdwinGuzman we get the status from Sierra as well (ex. https://github.com/NYPL/research-catalog/blob/ae9dee52f7be3dbe65415c3857b5259bdee1e5b7/pages/api/account/helpers.ts#L23). The user is never seeing any of this, so how we handle this would really just be for dev troubleshooting, and I think it makes sense that we just pass whatever Sierra's saying straight through. I'm wary of misleading in the docs by saying it's "most likely" for this reason bc we just have seen so much unexpected stuff, there's a lot of reasons why a checkout couldn't be renewed in particular

2024-03-29 19:19 UTC, EdwinGuzman commented
Yeah, that's fair. If you catch all the errors so the user never sees it, that's great. For whatever reason a checkout couldn't be renewed, or another error happens in Sierra, it's not that step that I'm concerned about but rather that it's still 403 for the client. When there is an auth issue, 403 is fine but 400 might be better for a bad request.

`updatePin` does pass whatever error code is returned from the Sierra call, but it's not being caught so in this case this would be an uncaught error situation. What I mean happens here https://github.com/NYPL/research-catalog/blob/ae9dee52f7be3dbe65415c3857b5259bdee1e5b7/pages/api/account/update-pin/%5Bid%5D.ts#L31 there's no try/catch for this error.

If you do catch the error, what I'm getting at is that 400 might be a better status code:

```
if (patronId == cookiePatronId) {
  try {
    const response = await updatePin(patronId, barcode, oldPin, newPin)
    responseStatus = response.status
    responseMessage = response.message
  } catch (e) {
    responseStatus = 400
    // This is a made up message but it could be `e.message`
    responseMessage = "Something went wrong updating the pin in Sierra"
} else {
  responseStatus = 403
  responseMessage = "Authenticated patron does not match request"
}
```

We can go over this on Monday. This does not block this PR.

2024-03-29 19:25 UTC, EdwinGuzman commented
I'm not going to delete the comment but ignore it. This _is_ happening and now I see what you're saying, it was just hard to read and I didn't catch it right away.

You're right, that it can be misleading in the docs because Sierra can return any status and any error message. I think "4XX" is more appropriate than "403" in the docs though because we know that the patron is authenticated when the call is made, but that the Sierra call itself had a different error.

2024-04-08 15:50 UTC, dgcohen approved these changes

2024-04-10 15:43 UTC, merged