SCC-4066 - Search results VQA Pt. 2
NYPL/research-catalog pull request #166
Opened 2024-04-11 19:02 UTC by dgcohen

Some more visual changes based on the last few items in the [VQA doc](https://docs.google.com/document/d/1qgHzrubMwxx_UvVu_hfVhDfbPEPPbgrypHv3BohSPtI/edit#heading=h.wq30kg5jzx41).

Specifically:

1. Search Results Card - Multiple Items + Available Online Links
2. DRB Sidebar
3. Pagination
4. Refine Search Dropdown

2024-04-11 19:03 UTC, dgcohen commented on pages/search/index.tsx
> -          /**
This is not related to VQA but a small bug fix I noticed in passing. Fixes an issue where there was no loading state after searching from a no results page. Let me know if you'd like me to move this to a separate PR.

2024-04-11 19:03 UTC, dgcohen commented on styles/components/Search.module.scss
> +
This is a DS styling override, maybe we should see whether this should be implemented there?

2024-04-12 14:09 UTC, charmingduchess commented
I don't know exactly where the styling for this is, but I'm seeing a larger space between rows in the single result card than is specified in the vqa doc.

2024-04-12 14:48 UTC, dgcohen commented
> I don't know exactly where the styling for this is, but I'm seeing a larger space between rows in the single result card than is specified in the vqa doc. Also, the space between DRB title and read online button looks smaller than the VQA doc.

I believe the single result VQA fixes are part of Edwin's PR (pt.1 ). Not sure I'm seeing the same issue with the DRB title spacing, looks like 24px on my local and vercel.

2024-04-12 16:17 UTC, charmingduchess commented
I think the thing with the spacing on DRB results is a thing when there isn't an author listed, which isn't a scenario outlined in the doc. If Apoorva doesn't flag it I guess it's not a big deal. 
<img width="242" alt="Screenshot 2024-04-12 at 12 17 24 PM" src="https://github.com/NYPL/research-catalog/assets/86011349/1b85a953-8707-47cb-979c-c88d691ac638">

2024-04-12 16:18 UTC, charmingduchess approved these changes
LGTM 🔥

2024-04-12 17:15 UTC, EdwinGuzman requested changes
Some minor updates.

2024-04-12 17:15 UTC, EdwinGuzman commented on src/components/DRB/DRBCard.tsx
> +    <Card backgroundColor="white" p="s" borderRadius="5px">
Use `ui.white`.

2024-04-12 17:15 UTC, EdwinGuzman commented on src/components/SearchResult/ElectronicResourcesLink.tsx
> +          fontWeight="bold"
This should be medium.

2024-04-12 17:15 UTC, EdwinGuzman commented on src/components/DRB/DRBContainer.tsx
> +      <CardHeading level="h6">
I think this should be an h2 to be on the same level as the "Displaying 1-50 of ...." text. The VQA doc says it's in the _style_ of h6 so do `size="h6"` instead.

2024-04-12 18:38 UTC, EdwinGuzman approved these changes

2024-04-12 19:22 UTC, merged