SCC-3745 - Add jest and react testing library
NYPL/research-catalog pull request #25
Opened 2023-09-19 16:26 UTC by dgcohen

This PR adds Jest and React Testing Library as well as the initial config.

The latest version of RTL requires React 18 so I installed version 12.1.5 for now which compatible with React 17.

I also added 2 basic tests for testing the initial config but there is currently no minimum coverage required.

2023-09-20 16:01 UTC, EdwinGuzman requested changes
Some updates. I personally prefer colocating the test file with the component file but that's a good question to bring up with the team.

2023-09-20 18:03 UTC, charmingduchess approved these changes

2023-09-21 16:36 UTC, dgcohen commented on .husky/pre-commit
> +npm run test
Good call, happy to get rid of this also since it can be annoying.

2023-09-21 16:38 UTC, dgcohen commented
> Some updates. I personally prefer colocating the test file with the component file but that's a good question to bring up with the team.

Yeah I was thinking of doing that initially, might be nice to have them live near the components.

2023-09-25 21:12 UTC, EdwinGuzman approved these changes

2023-09-26 14:45 UTC, merged