Scc 383 x/vqa
NYPL/research-catalog pull request #38
Opened 2023-10-26 21:42 UTC by charmingduchess

This combines work called out in 3 VQA tickets, including:

-  Page title changed to “NYPL Research Catalog”. Prod is currently “Research Catalog | NYPL”.  
-  Article Search link is missing. 
- If possible, the subnav on mobile (375px and below) should bleed over onto a second line as shown. However the crowding issue will be eliminated with the upcoming change from ‘subject heading explorer’ to ‘browse’, so I’d leave it as is if it’s a big effort. 
   - Note this one i did not follow the spec 100%, but instead implemented a simpler fix... TBD if it is acceptable.
- Placeholder text in the text input field (Keyword, title…etc) should be italicized.
- An ‘X’ clear button should appear in the text input field once the patron starts typing - I believe this functionality exists in the DS search bar, but let me know if that isn’t the case. 
- The spacing between the ‘advanced search’ button and the bottom of the gray box should be 16px on both desktop and mobile.

2023-10-27 19:07 UTC, EdwinGuzman requested changes
Just one update needed to remove the search value from the internal state.

2023-10-27 19:07 UTC, EdwinGuzman commented on src/components/SearchForm/SearchForm.tsx
> +              isClearable: true,
This is also missing a call to clear the value from the internal state. This is noticeable when you try this:
1. Search for "spaghetti"
2. Click on the clear X button
3. Click on "Search"

This returns 426 results for "spaghetti". The value is removed from the search display but is still in the state. You can pass in `isClearableCallback` and pass in a call to `setSearchTerm("")`.

2023-10-31 13:35 UTC, dgcohen approved these changes
Agree with Edwin's comment, but otherwise looks good to me.

2023-11-01 16:43 UTC, EdwinGuzman commented on src/components/SearchForm/SearchForm.tsx
> +              isClearable: true,
That sounds great, thanks.

2023-11-01 16:43 UTC, EdwinGuzman approved these changes

2023-11-03 19:39 UTC, merged