My Account 2.0
NYPL/research-catalog pull request #407
Opened 2024-11-26 16:22 UTC by 7emansell

## Ticket:

- Updated phone, email, notification preference and home library to be individually editable in Account Settings (SCC-4337, SCC-4254, SCC-4253)
- Updated username to be editable in My Account header (SCC-4236)

## This PR does the following:

## How has this been tested?

## Accessibility concerns or updates

### Checklist:

- [x] I updated the CHANGELOG with the appropriate information and JIRA ticket number (if applicable).
- [x] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

2024-11-26 17:09 UTC, charmingduchess requested changes
A couple small things that are not _super_ crucial, so if you can include those that would be great. But the API client needs to be updated before this can go out.

2024-11-26 17:09 UTC, charmingduchess commented on src/server/nyplApiClient/index.ts
>    if (CACHE.clients[apiName]) {
can you update this cache to include the version? otherwise i fear this may return a cached v0.1 client when you want a v0.3

2024-11-26 17:50 UTC, 7emansell commented on src/components/MyAccount/Settings/PasswordForm.test.tsx
> +  test("successfully sets patron data if every field is valid", async () => {
What might make more sense as the title for this test?

2024-11-26 17:50 UTC, 7emansell commented on src/components/MyAccount/Settings/PasswordForm.test.tsx
> +  test("sets failure if current password is wrong", async () => {
`test` is the same as `it`, updated

2024-11-26 17:52 UTC, 7emansell commented on pages/api/account/username/[id].ts
> +    return res.status(responseStatus).json(responseMessage)
This is the structure of all of these handlers, and it returns the 403 quicker without trying the options below.

2024-11-27 01:18 UTC, EdwinGuzman approved these changes
There are updates needed but approving to start the QA process.

2024-11-27 01:18 UTC, EdwinGuzman commented on src/components/MyAccount/Settings/UsernameForm.test.tsx
> +  it("renders correctly with when user has no username", () => {
I agree there should be more tests but they can also be written while the team starts the QA cycle.

2024-11-27 14:08 UTC, charmingduchess approved these changes

2024-11-27 15:24 UTC, merged